phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: a15e7673541734e7ed9c63a4a4dd9833
  file_format: html

  push:
    sources:
    - file: ./index_en-US.html
      params:
        locale_id: 16bfb780da6b0a435d91995091991148
        update_translations: true 
        
  pull:
    targets:
    - file: ./index_<locale_code>.json
      params:
        file_format: simple_JSON
        locale_id: 0d46a086a00854f892b89a78508edb23
        include_empty_translations: true 
        fallback_locale_id: 16bfb780da6b0a435d91995091991148
        
  pull:
    targets:
    - file: ./index_<locale_code>.json
      params:
        file_format: simple_JSON
        locale_id: 06a1cfb9a84b1c121474c6dec483d28c
        include_empty_translations: true 
        fallback_locale_id: 16bfb780da6b0a435d91995091991148
